In [1]:
import numpy as np
import pandas as pd

In [ ]:
df_s = pd.DataFrame(dict(v1 = [100, 200, 300], v2 = [400, 500, 600], shape=["A", "B", "C"]))
df_s

df_s.iloc[:2, ]
df_s.loc[:2, ]

df_s.v1

df_s.shape
df_s["shape"]

df_s.iloc[:, :-1]
df_s.loc[:, "v2":]

In [ ]:
df_s.loc[df_s["v1"] == 200, ]
df_s.loc[df_s["v1"] != 200, ]
df_s["v1"] == 200
~(df_s["v1"] == 200)
df_s.loc[~(df_s["v1"] == 200), ]
df_s.loc[(df_s["v1"] == 200) & (df_s["v2"] == 600), ]
df_s.loc[(df_s["v1"] == 200) | (df_s["v2"] == 600), ]

condi1 = df_s["v1"] == 200
condi2 = df_s["v2"] == 500
df_s.loc[condi1 & condi2, ]

df_s.loc[(df_s["shape"] == "A") | (df_s["shape"] == "C"), ]
df_s.loc[df_s["shape"].isin(["A", "C"]), ]
df_s.loc[~df_s["shape"].isin(["A", "C"]), ]

df_s.loc[]

In [ ]:
df = pd.read_csv("./dataset/krx_202105_utf8.csv")
df.head(2)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub

In [ ]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

In [ ]:
df["종가"].idxmax()

In [ ]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

In [ ]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

In [ ]:
# 결측치 처리

In [ ]:
df = pd.read_csv("./dataset/iris_missing.csv")
df_sub = df.head()
df_sub.info()
df_sub.dtypes

In [ ]:
df_sub

In [ ]:
df_sub.count()

In [ ]:
df_sub.isna()

In [ ]:
df_sub.isna().sum()

In [ ]:
df_sub.isna().sum(axis=1)

In [ ]:
df_sub1 = df_sub.loc[df_sub["Sepal.Width"].isna(), ]
df_sub1

In [ ]:
df_sub2 = df_sub.loc[df_sub["Sepal.Width"].notna(), ]
df_sub2

In [ ]:
df_sub3 = df_sub.dropna()
df_sub3

In [ ]:
df_sub.loc[:, "Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())
df_sub # 3.0 이전 버전은 경고가 뜰 수 있다

In [ ]:
df_sub2 = df.tail(3)
df_sub2

In [ ]:
df_sub2.reset_index()

In [ ]:
df_sub2.reset_index(drop=True)

In [ ]:
df_sub2.set_index("Species")

In [1]:
# 원소/조합 세기

In [2]:
df = pd.read_csv("./dataset/bike.csv")
df.head(1)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16

In [3]:
df["season"].unique()

array([1, 2, 3, 4])

In [4]:
df["season"].drop_duplicates()

0       1
1323    2
2690    3
4055    4
Name: season, dtype: int64

In [5]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [6]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [ ]:
# group by

In [9]:
df = pd.read_csv("./dataset/diamonds.csv")
df.head(2)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [11]:
df.groupby("cut")["depth"].max()
# 대상 변수가 2개 이상이 아니면 시리즈로 나옴

cut
Fair         79.0
Good         67.0
Ideal        66.7
Premium      63.0
Very Good    64.9
Name: depth, dtype: float64

In [14]:
df_g1 = df.groupby("cut")["depth"].max().reset_index()
df_g1

         cut  depth
0       Fair   79.0
1       Good   67.0
2      Ideal   66.7
3    Premium   63.0
4  Very Good   64.9

In [15]:
df.groupby("cut")[["depth", "x"]].max()

           depth      x
cut
Fair        79.0  10.74
Good        67.0   9.44
Ideal       66.7   9.65
Premium     63.0  10.14
Very Good   64.9  10.01

In [18]:
series_g2 = df.groupby(["cut", "color"])["x"].max()
series_g2.head()
# 얘는 기준 변수가 2개라서 시리즈로 나와

cut   color
Fair  D         9.42
      E         8.16
      F         8.58
      G         8.75
      H        10.00
Name: x, dtype: float64

In [19]:
df_g2 = df.groupby(["cut", "color"])["x"].max().reset_index()
df_g2.head()

    cut color      x
0  Fair     D   9.42
1  Fair     E   8.16
2  Fair     F   8.58
3  Fair     G   8.75
4  Fair     H  10.00

In [20]:
df_g3 = df.groupby("cut")["y"].agg(["min", "max"]).reset_index()
df_g3

         cut  min    max
0       Fair  0.0  10.54
1       Good  0.0   9.38
2      Ideal  0.0  31.80
3    Premium  0.0  58.90
4  Very Good  0.0   9.94

In [21]:
df_g4 = df.groupby("cut")[["x", "y"]].agg({"x": "min", "y": "max"}).reset_index()
df_g4

         cut    x      y
0       Fair  0.0  10.54
1       Good  0.0   9.38
2      Ideal  0.0  31.80
3    Premium  0.0  58.90
4  Very Good  0.0   9.94

In [25]:
df_tx = pd.DataFrame(dict(v1 = [100, 200, 300],
                         v2 = ["abc", "aaa", "ccc"],
                         v3 = [123, "1234-5678", "010-1234-5678"]))
df_tx

    v1   v2             v3
0  100  abc            123
1  200  aaa      1234-5678
2  300  ccc  010-1234-5678

In [31]:
df_tx["v2"].replace("a", "!")

0    abc
1    aaa
2    ccc
Name: v2, dtype: object

In [32]:
df_tx["v2"].str.replace("a", "!")

0    !bc
1    !!!
2    ccc
Name: v2, dtype: object

In [35]:
df_tx["v4"] = df_tx["v3"].astype("str")
df_tx["v4"].str.split("-").explode()

0     123
1    1234
1    5678
2     010
2    1234
2    5678
Name: v4, dtype: object

In [43]:
ser_t = pd.Series([20241218, 20241219])
pd.to_datetime(ser_t)
# pd.to_datetime(ser_t.astype("str"))

0   1970-01-01 00:00:00.020241218
1   1970-01-01 00:00:00.020241219
dtype: datetime64[ns]

In [48]:
df = pd.read_csv("./dataset/elec_load_2017_7d.csv")
df.head(2)

,YEAR,MONTH,DAY,X1HR,X2HR,X3HR,X4HR,X5HR,X6HR,X7HR,...,X15HR,X16HR,X17HR,X18HR,X19HR,X20HR,X21HR,X22HR,X23HR,X24HR
0,2017,1,1,60178,57862,56165,55135,54450,54401,54147,...,49213,49357,50362,53115,55205,55437,55348,55790,58195,59330
1,2017,1,2,57067,55148,53983,53571,54027,55388,57753,...,72228,71945,72641,73387,72294,69989,67893,66504,67435,69275

In [45]:
df_m1 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"])
df_m1

     YEAR  MONTH  DAY variable  value
0    2017      1    1     X1HR  60178
1    2017      1    2     X1HR  57067
2    2017      1    3     X1HR  66263
3    2017      1    4     X1HR  68403
4    2017      1    5     X1HR  68053
..    ...    ...  ...      ...    ...
163  2017      1    3    X24HR  71346
164  2017      1    4    X24HR  70834
165  2017      1    5    X24HR  66687
166  2017      1    6    X24HR  63214
167  2017      1    7    X24HR  69219

[168 rows x 5 columns]

In [47]:
df_m2 = df.melt(id_vars = ["YEAR", "MONTH", "DAY"],
               var_name="HOUR", value_name="load")
df_m2

     YEAR  MONTH  DAY   HOUR   load
0    2017      1    1   X1HR  60178
1    2017      1    2   X1HR  57067
2    2017      1    3   X1HR  66263
3    2017      1    4   X1HR  68403
4    2017      1    5   X1HR  68053
..    ...    ...  ...    ...    ...
163  2017      1    3  X24HR  71346
164  2017      1    4  X24HR  70834
165  2017      1    5  X24HR  66687
166  2017      1    6  X24HR  63214
167  2017      1    7  X24HR  69219

[168 rows x 5 columns]

In [52]:
df_m2["h1"] = df_m2["HOUR"].str.replace("X", "").str.replace("HR", "")
df_m2["h2"] = df_m2["HOUR"].str.replace("X|HR", "", regex=True)
df_m2["h3"] = df_m2["HOUR"].str.replace("[A-Z]", "", regex=True)
df_m2["h4"] = df_m2["HOUR"].str.replace("[^0-9]", "", regex=True)
df_m2

     YEAR  MONTH  DAY   HOUR   load  h1  h2  h3  h4
0    2017      1    1   X1HR  60178   1   1   1   1
1    2017      1    2   X1HR  57067   1   1   1   1
2    2017      1    3   X1HR  66263   1   1   1   1
3    2017      1    4   X1HR  68403   1   1   1   1
4    2017      1    5   X1HR  68053   1   1   1   1
..    ...    ...  ...    ...    ...  ..  ..  ..  ..
163  2017      1    3  X24HR  71346  24  24  24  24
164  2017      1    4  X24HR  70834  24  24  24  24
165  2017      1    5  X24HR  66687  24  24  24  24
166  2017      1    6  X24HR  63214  24  24  24  24
167  2017      1    7  X24HR  69219  24  24  24  24

[168 rows x 9 columns]

In [54]:
df = pd.read_csv("./dataset/diamonds.csv")
df.head(1)

   carat    cut color clarity  depth  table  price     x     y     z
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

In [56]:
df_agg1 = df.pivot_table(index="color", columns="cut", values="carat", aggfunc="min")
df_agg1

cut    Fair  Good  Ideal  Premium  Very Good
color
D      0.25  0.23   0.20     0.20       0.23
E      0.22  0.23   0.20     0.20       0.20
F      0.25  0.23   0.23     0.20       0.23
G      0.23  0.23   0.23     0.23       0.23
H      0.33  0.25   0.23     0.23       0.23
I      0.41  0.30   0.23     0.23       0.24
J      0.30  0.28   0.23     0.30       0.24

In [58]:
df_agg2 = df.groupby(["color", "cut"])["carat"].min().reset_index()
df_agg2.head()

  color        cut  carat
0     D       Fair   0.25
1     D       Good   0.23
2     D      Ideal   0.20
3     D    Premium   0.20
4     D  Very Good   0.23

In [60]:
df_bike = pd.read_csv("./dataset/bike.csv")
df_b1 = df_bike.iloc[:4, 4:7]
df_b2 = df_bike.iloc[1:5, 5:8]

In [64]:
df_b1

   weather  temp   atemp
0        1  9.84  14.395
1        1  9.02  13.635
2        1  9.02  13.635
3        1  9.84  14.395

In [70]:
df_b2.reset_index(drop=True)

   temp   atemp  humidity
0  9.02  13.635        80
1  9.02  13.635        80
2  9.84  14.395        75
3  9.84  14.395        75

In [61]:
pd.concat([df_b1, df_b2])

   weather  temp   atemp  humidity
0      1.0  9.84  14.395       NaN
1      1.0  9.02  13.635       NaN
2      1.0  9.02  13.635       NaN
3      1.0  9.84  14.395       NaN
1      NaN  9.02  13.635      80.0
2      NaN  9.02  13.635      80.0
3      NaN  9.84  14.395      75.0
4      NaN  9.84  14.395      75.0

In [66]:
pd.concat([df_b1, df_b2], axis=1)

   weather  temp   atemp  temp   atemp  humidity
0      1.0  9.84  14.395   NaN     NaN       NaN
1      1.0  9.02  13.635  9.02  13.635      80.0
2      1.0  9.02  13.635  9.02  13.635      80.0
3      1.0  9.84  14.395  9.84  14.395      75.0
4      NaN   NaN     NaN  9.84  14.395      75.0