In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor

In [10]:
df = pd.read_csv("./test/set_01_data.csv")
df.head(5)

,Id,Stars,Ratings,Reviews,current_price,MRP,channel,Operating_system,Picture_quality,Speaker,Frequency
0,TCL_016,4.3,0,0,39990,89990,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,60 Hz Refresh Rate
1,Onix_001,4.8,0,0,32222,38790,Full HD 1980 x 1080 Pixels,16 W Speaker Output,60 Hz Refresh Rate,2 x HDMI | 2 x USB,1 Year Warranty on Product
2,SAMSUNG_044,0.0,0,0,45785,45900,Netflix|Disney+Hotstar|Youtube,Operating System: Tizen,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate
3,MOTOROLA_012,4.4,9687,1532,62999,79999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,50 W Speaker Output,60 Hz Refresh Rate
4,LG_068,4.1,0,0,77900,77900,Operating System: WebOS,Full HD 1920 x 1080 Pixels,20 W Speaker Output,50 Hz Refresh Rate,3 x HDMI | 2 x USB

In [11]:
df["F1"] = np.where(df["Frequency"].str.contains("Hz"), df["Frequency"].str.replace("[^0-9]", "", regex=True), np.nan)
df["F2"] = np.where(df["Picture_quality"].str.contains("Hz"), df["Picture_quality"].str.replace("[^0-9]", "", regex=True), np.nan)
df["F3"] = np.where(df["Speaker"].str.contains("Hz"), df["Speaker"].str.replace("[^0-9]", "", regex=True), np.nan)
df.head(5)

,Id,Stars,Ratings,Reviews,current_price,MRP,channel,Operating_system,Picture_quality,Speaker,Frequency,F1,F2,F3
0,TCL_016,4.3,0,0,39990,89990,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,60 Hz Refresh Rate,60,NaN,NaN
1,Onix_001,4.8,0,0,32222,38790,Full HD 1980 x 1080 Pixels,16 W Speaker Output,60 Hz Refresh Rate,2 x HDMI | 2 x USB,1 Year Warranty on Product,NaN,60,NaN
2,SAMSUNG_044,0.0,0,0,45785,45900,Netflix|Disney+Hotstar|Youtube,Operating System: Tizen,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate,60,NaN,NaN
3,MOTOROLA_012,4.4,9687,1532,62999,79999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,50 W Speaker Output,60 Hz Refresh Rate,60,NaN,NaN
4,LG_068,4.1,0,0,77900,77900,Operating System: WebOS,Full HD 1920 x 1080 Pixels,20 W Speaker Output,50 Hz Refresh Rate,3 x HDMI | 2 x USB,NaN,NaN,50

In [13]:
df["Freq"] = np.where(df["F1"].isna(), np.where(df["F2"].isna(), df["F3"], df["F2"]), df["F1"])
df.head(5)

,Id,Stars,Ratings,Reviews,current_price,MRP,channel,Operating_system,Picture_quality,Speaker,Frequency,F1,F2,F3,Freq
0,TCL_016,4.3,0,0,39990,89990,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,60 Hz Refresh Rate,60,NaN,NaN,60
1,Onix_001,4.8,0,0,32222,38790,Full HD 1980 x 1080 Pixels,16 W Speaker Output,60 Hz Refresh Rate,2 x HDMI | 2 x USB,1 Year Warranty on Product,NaN,60,NaN,60
2,SAMSUNG_044,0.0,0,0,45785,45900,Netflix|Disney+Hotstar|Youtube,Operating System: Tizen,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate,60,NaN,NaN,60
3,MOTOROLA_012,4.4,9687,1532,62999,79999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,50 W Speaker Output,60 Hz Refresh Rate,60,NaN,NaN,60
4,LG_068,4.1,0,0,77900,77900,Operating System: WebOS,Full HD 1920 x 1080 Pixels,20 W Speaker Output,50 Hz Refresh Rate,3 x HDMI | 2 x USB,NaN,NaN,50,50

In [23]:
df_60 = df.loc[df["Freq"] == "60", ]
len(df_60)

493

In [ ]:
# Question 1 - Answer

In [81]:
df = pd.read_csv("./test/set_01_data.csv")
df_q1 = df.loc[:,["Frequency", "Picture_quality", "Speaker"]]
df_q1["h1"] = df_q1["Frequency"].str.contains("Hz") + 0
df_q1["h2"] = df_q1["Picture_quality"].str.contains("Hz") + 0
df_q1["h3"] = df_q1["Speaker"].str.contains("Hz") + 0
df_q1["hz_cnt"] = df_q1["h1"]+df_q1["h2"]+df_q1["h3"]
df_q1.head()

,Frequency,Picture_quality,Speaker,h1,h2,h3,hz_cnt
0,60 Hz Refresh Rate,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,1,0,0,1
1,1 Year Warranty on Product,60 Hz Refresh Rate,2 x HDMI | 2 x USB,0,1,0,1
2,60 Hz Refresh Rate,Full HD 1920 x 1080 Pixels,20 W Speaker Output,1,0,0,1
3,60 Hz Refresh Rate,Ultra HD (4K) 3840 x 2160 Pixels,50 W Speaker Output,1,0,0,1
4,3 x HDMI | 2 x USB,20 W Speaker Output,50 Hz Refresh Rate,0,0,1,1

In [82]:
# Question 2
df = pd.read_csv("./test/set_01_data.csv")

df_sub = df.loc[df["Picture_quality"].str.contains("4K") | df["Operating_system"].str.contains("4K") | df["channel"].str.contains("4K"), ]
df_sub = df_sub.loc[(df_sub["Stars"] != 0) & (df_sub["Ratings"] != 0) & (df_sub["Reviews"] != 0), ]
df_sub = df_sub.loc[:, ["Stars", "Ratings", "Reviews", "current_price", "MRP"]].reset_index(drop = True)
df_sub.head()

   Stars  Ratings  Reviews  current_price    MRP
0    4.4     9687     1532          62999  79999
1    4.5    17462     5306          54999  69999
2    4.2     1110      177          28490  39990
3    4.4    31993     4975          54999  75000
4    4.3    11336     1966          33999  45999

In [89]:
kmeans = KMeans(n_clusters=3, random_state=123).fit(df_sub)

In [90]:
kmeans.labels_

array([0, 0, 2, 0, 2, 0, 2, 0, 2, 1, 1, 2, 2, 2, 2, 0, 2, 0, 1, 2, 0, 0,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1,
       2, 2, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2,
       0, 1, 1, 0, 0, 1, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 1, 0, 2, 0, 0, 2,
       0, 0, 2, 1, 2, 0, 1, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0,
       0, 2, 2], dtype=int32)

In [91]:
df_sub["cluster"] = kmeans.labels_
df_sub["cluster"].value_counts()

cluster
2    55
0    44
1    14
Name: count, dtype: int64

In [95]:
# Question 3
df = pd.read_csv("./test/set_01_data.csv")
df.head(5)

,Id,Stars,Ratings,Reviews,current_price,MRP,channel,Operating_system,Picture_quality,Speaker,Frequency
0,TCL_016,4.3,0,0,39990,89990,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,30 W Speaker Output,60 Hz Refresh Rate
1,Onix_001,4.8,0,0,32222,38790,Full HD 1980 x 1080 Pixels,16 W Speaker Output,60 Hz Refresh Rate,2 x HDMI | 2 x USB,1 Year Warranty on Product
2,SAMSUNG_044,0.0,0,0,45785,45900,Netflix|Disney+Hotstar|Youtube,Operating System: Tizen,Full HD 1920 x 1080 Pixels,20 W Speaker Output,60 Hz Refresh Rate
3,MOTOROLA_012,4.4,9687,1532,62999,79999,Netflix|Prime Video|Disney+Hotstar|Youtube,Operating System: Android,Ultra HD (4K) 3840 x 2160 Pixels,50 W Speaker Output,60 Hz Refresh Rate
4,LG_068,4.1,0,0,77900,77900,Operating System: WebOS,Full HD 1920 x 1080 Pixels,20 W Speaker Output,50 Hz Refresh Rate,3 x HDMI | 2 x USB

In [103]:
df = df.loc[(~df["channel"].str.contains("Oper|Pixel")), ]
df["ReviewRate"] = df["Reviews"] / df["Ratings"]
df["Discount"] = df["current_price"] / df["MRP"]
# df["Netflix"] = np.where(df["channel"].str.contains("Netflix"), 1, 0)
df["Netflix"] = df["channel"].str.contains("Netflix") + 0
# df["Prime"] = np.where(df["channel"].str.contains("Prime"), 1, 0)
df["Netflix"] = df["channel"].str.contains("Prime") + 0
# df["Quality"] = np.where(df["Picture_quality"].str.contains("4K|8K"), 1, 0)
df["Quality"] = df["Picture_quality"].str.contains("4K|8K") + 0

df = df.dropna() # 이거도 뒤에서 컬럼 필터링 한 다음에 해주는게 좋을 듯!!!
len(df)

200

In [111]:
# df_3 = df.loc[:, ["ReviewRate", "MRP", "Discount", "Netflix", "Prime", "Quality"]].reset_index(drop = True)
df_3 = df[["Stars", "ReviewRate", "MRP", "Discount", "Netflix", "Prime", "Quality"]].reset_index(drop = True)
# reset은 위에서 필터링 할 때 미리 해주면 좋을 듯

df_3.head()

   Stars  ReviewRate    MRP  Discount  Netflix  Prime  Quality
0    4.4    0.158150  79999  0.787497        1      1        1
1    4.5    0.303860  69999  0.785711        1      1        1
2    4.2    0.159459  39990  0.712428        1      1        1
3    4.4    0.155503  75000  0.733320        0      0        1
4    4.3    0.173430  45999  0.739125        1      1        1

In [112]:
random = RandomForestRegressor(random_state=123).fit(df_3.drop(columns = "Stars"), df_3[["Stars"]])

/Users/ttochi/repo/data-science/.venv/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [114]:
arr_MDI = random.feature_importances_
arr_MDI

array([0.28844088, 0.20221363, 0.46843043, 0.0113683 , 0.01476839,
       0.01477839])

In [116]:
pd.Series(arr_MDI, index = df_3.columns[1:])

ReviewRate    0.288441
MRP           0.202214
Discount      0.468430
Netflix       0.011368
Prime         0.014768
Quality       0.014778
dtype: float64